template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  appenders:
    - type: console
      threshold: WARN
      target: stderr